name: CLA verification
on:
  pull_request_target:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  cla-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - id: 'query-worksheet'
        uses: jroehl/gsheet.action@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: |
            [
              { "command": "getData", "args": { "range": "'Form Responses 1'!F:F" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Find username
        id: set-variables
        shell: bash
        run: |
          if [[ github.event_name == 'pull_request' ]]; then
              echo "::set-output name=username::${{ github.event.pull_request.user.login }}"
          else
              echo "::set-output name=username::${{ github.event.issue.user.login }}"
          fi
      - name: Find username index
        id: username-index
        env:
          RESULTS: ${{ steps.query-worksheet.outputs.results }}
          GITHUB_USER_NAME: ${{ steps.set-variables.outputs.username }}
        shell: bash
        run: |
          index=`echo "$RESULTS" | jq -c '.results[].result.rawData | flatten | index(env.GITHUB_USER_NAME)'`
          echo $GITHUB_USER_NAME
          echo $index
          [ "$index" = "null" ] && echo "Username not found in list"
          echo "::set-output name=index::$index"
      - name: Add CLA Label and Comment
        if: |
          steps.username-index.outputs.index == 'null' && 
          ((github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'CLA')) ||
          (github.event_name == 'issue_comment' && !contains(github.event.issue.labels.*.name, 'CLA')))
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hi @${{ steps.set-variables.outputs.username }},\n\nWelcome to GluonHQ and thank you for taking time to contribute to this project.\n\nWe do not recognise you as a contributor. Can you please sign [Gluon Individual Contributor License Agreement](https://cla.gluonhq.com) ?'
            })
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['CLA']
            })
      - name: Add CLA-VERIFIED Label
        if: |
          steps.username-index.outputs.index != 'null' &&
          ((github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'CLA-VERIFIED')) ||
          (github.event_name == 'issue_comment' && !contains(github.event.issue.labels.*.name, 'CLA-VERIFIED')))
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['CLA-VERIFIED']
            })
      - name: Remove CLA Label
        if: | 
          steps.username-index.outputs.index != 'null' &&
          ((github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'CLA')) ||
          (github.event_name == 'issue_comment' && contains(github.event.issue.labels.*.name, 'CLA')))
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'CLA'
            })
